config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'sets/index'
  post 'sets/upload_file' => 'sets#upload_file'
  post 'sets/download_file' => 'sets#download_file'
  root "items#index"
  resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :item_categories
  has_many :items ,through: :item_categories
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :item_categories
  has_many :categories, through: :item_categories
  #searchkick
  validates :question, :answer, presence: true
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :authenticate_user!, except: [:index,:show]
before_action :set_item, :only => [:show,:edit,:update,:destroy]

  def index

    #if params[:search].present?
    #@items = Item.search(params[:search], page: params[:page], per_page: 5)
    #else
    @items = Item.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
    #end
    @item = Item.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    respond_to do |response|
      if @item.save
        response.html {redirect_to @item}
        response.js
      else
        response.html {render 'new'}
        response.js
      end
    end

  end

  def edit
  end

  def update
    respond_to do |response|
      if @item.update(item_params)
        response.html {redirect_to @item}
        response.js
      else
        response.html {render 'edit'}
        response.js
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |response|
        response.html {redirect_to items_path}
        response.js
    end
  end


  def show
  end



  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:question,:answer,:category_ids => [])
  end

end

app/controllers/sets_controller.rb
class SetsController < ApplicationController
  def index
  end

  def upload_file
    uploadedFile = params[:upload][:file]
    File.open(Rails.root.join('saved_files',uploadedFile.original_filename), 'wb') do |f|
      f.write(uploadedFile.read)
    end

    redirect_to sets_index_path
  end

  def download_file
    fileName = params[:download][:fileName]
    send_file Rails.root.join('saved_files',fileName)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sets_helper.rb
module SetsHelper
end

app/views/items/_createModal.html.erb
<!-- Modal -->
<div class="modal fade" id="myCreateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create a new entry!</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@item,:remote => true ) do |f| %>
        <div class="field">
          <%= f.label :question %> <br>
          <%= f.text_area :question ,:class => "form-control item-question", :required => true %>
        </div>
        <br>
        <div class="field">
          <%= f.label :answer %> <br>
          <%= f.text_area :answer , :class => "form-control item-answer" , :required => true  %>
        </div>
        <br>
        <div class="field">
          <%=f.label :category_id  %> <br>
          <%= f.collection_select :category_ids, Category.order(:name), :id, :name,{ include_blank: true },
         { multiple:true,class: 'chosen-select item-category', 'data-placeholder': " " }  %>
        </div>
      </div>
      <br>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Create", :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = '<%= url_for(item_url)%>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @item.id %>' // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://hashquestion.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/items/_item.html.erb
<div class="col-md-8" id="item_<%= item.id %>">

  <div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <pre><label>Q:</label>&nbsp&nbsp<%= item.question.html_safe %></pre>


        <a data-toggle="collapse" href="#collapse_<%= item.id %>" class= "btn btn-default">View Answer</a>
        <small style="opacity:0.5">&nbsp&nbspcourtesy: <%= item.user.username ||= item.user.email %></small>
      </h4>
    </div>
    <div id="collapse_<%= item.id %>" class="panel-collapse collapse">
      <div class="panel-body"><label>A:</label>&nbsp&nbsp<%= item.answer.html_safe %>


      </div>
      <div class="panel-footer">

        <div class="btn-group" role="group" aria-label="...">
          <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatepost_<%= item.id %>">
            Edit
          </button>
          <%= link_to 'Disqus', item , :class => "btn btn-default" %>
          <%= link_to 'Delete', item, :method => :delete, :class => "btn btn-danger", :remote => true %>

        </div>

      </div>
    </div>
  </div>
</div>



  <!-- Modal - update posts -->
        <%= form_for(item, :method => :put, :remote => true) do |f| %>
        <div class="modal fade" id="myupdatepost_<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Edit this entry!</h4>
            </div>
            <div class="modal-body">

            <div class="field">
              <%= f.label :question %><br>
              <%= f.text_area :question, :class => "form-control" , :required => true %>
            </div>
            <div class="field">
              <%= f.label :answer %><br>
              <%= f.text_area :answer, class: "form-control" , :required => true %>
            </div>
            <div class="field" >
              <%=f.label :category_id  %> <br>
              <%= f.collection_select :category_ids, Category.order(:name), :id, :name,{ include_blank: true },
             { multiple:true,class: 'chosen-select', 'data-placeholder': " "  }  %>
            </div>
            </div>
            <div class="modal-footer">
              <button type="button" id="myupdatebutton_<%= item.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= submit_tag "Update", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        </div>
        <% end %>
  <!-- Modal -->
</div>

app/views/items/create.js.erb
$("#myCreateModal").modal('hide');
$('.item-question').val('');
$(".item-answer").val('');
$(".item-category").val('').trigger('chosen:updated');;

$('#container_items').prepend("<%= j(render @item).html_safe %>").trigger("turbolinks:load");
$("#item_<%= @item.id %>").hide().fadeIn(1000);

app/views/items/destroy.js.erb
$("#item_<%= @item.id %>").fadeOut(500,function(){
  $(this).remove();
});

app/views/items/index.html.erb
<%= render 'components/jumbotron'  %>

<div class="container">
  <!-- Trigger the modal with a button -->
<div class="row">
  <div class="col-xs-6">
    <%= form_tag( items_path, :method => "get", role:"search") do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search HashQuesions" ,class:"form-control" %>
      <span class="input-group-btn">
       <%= submit_tag "Search", :name => nil,class: 'btn btn-default' %>

      </span>
    <% end %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->


  <div class="col-xs-6">
      <button type="button" class="btn btn-default btn-md" data-toggle="modal" data-target="#myCreateModal"><i class="fa fa-pencil" aria-hidden="true"></i> Add a Question! </button>
  </div><!-- /.col-lg-6 -->

</div>
<hr>

  <%= will_paginate @items, renderer: BootstrapPagination::Rails %>




  <div class="row" id= "container_items">
    <%= render @items %>
  </div>

  <%= will_paginate @items, renderer: BootstrapPagination::Rails %>
  <hr>

  <%= render 'createModal' %>





</div>

app/views/items/show.html.erb
<div class="container ">
  
  <br>
  <div class="well well-lg disqus-well">
    <label>Question:</label><br>
    <%=  @item.question.html_safe %><br>
    <hr>
    <label>Answer:</label><br>
    <%= @item.answer.html_safe %><br>

    <hr>
    <%= render 'disqus' %>
  </div>
</div>

app/views/items/update.js.erb
$("#myupdatepost_<%= @item.id %>").modal('hide');
$("#item_<%= @item.id %>").fadeOut(500,function(){
  $(this).remove();
  $("#container_items").prepend('<%= j render @item %>');
});

app/views/layouts/_aboutModal.html.erb
<!-- Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">About</h4>
      </div>
      <div class="modal-body" style="color:#ff554c">
        <h1 >Add questions and answers of ruby and rails to website!</h1>
        <h2>Discuss the questions and their explaination with the community for further clarity!</h2>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_contactModal.html.erb
<!-- Modal -->
<div class="modal fade " id="contactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contact</h4>
      </div>
      <div class="modal-body text-center" style="color:#ff554c">
        <h1>Ajinkya Devasthali</h1>
        <h3>https://github.com/ajex13</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success alert-dismissable'>
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger alert-dismissable'>
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HashQuestions</title>
     <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <link type="image/x-icon" href="favicon.ico" rel="icon" />
    <link type="image/x-icon" href="favicon.ico" rel="shortcut icon" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  </head>

  <body style="padding-top: 100px;">
    <%= render 'components/navbar' %>

    <div><%= render('layouts/messages.html.erb') %></div>

      <%= render 'layouts/aboutModal' %>
      <%= render 'layouts/contactModal' %>



    <%= yield %>
  </body>
</html>

app/views/sets/index.html.erb
<div class="container">
<br>
<pre>
  Contribute to this question library! Become an admin to add questions directly or upload a file here.
  We will examine the file and add questions on your behalf.
  Please provide the file in question/answer format.
</pre>
<br>
  <div class="panel panel-default">
    <div class="panel panel-heading">
      Upload a file
    </div>
    <div class="panel panel-body">
      <%=form_for :upload, url: sets_upload_file_path do |f|   %>
        <%= f.file_field :file  %>
        <hr>
        <%= f.submit :upload! ,class: "btn btn-default"%>
      <% end %>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel panel-heading">
      Download a file
    </div>
    <div class="panel panel-body">
      List of uploaded files:
      <%= form_for :download, url: sets_download_file_path do |f| %>
      <pre>
      <% Dir.foreach("saved_files") do |x| %>
      <%= "- #{x}" %>
      <% end %>

      </pre>
      <%= f.text_field :fileName , class: "form-control"%><br>
      <%= f.submit :download! ,class: "btn btn-default" %>
      <% end %>
    </div>
  </div>






</div>